// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flcawcmxpduuomowmqjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsY2F3Y214cGR1dW9tb3dtcWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjEwOTEsImV4cCI6MjA2MTIzNzA5MX0.D_xGLiXe8ynwQoMzIhsR5rMiz2H0GOavC8ivfQVZFEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);